from fastapi import APIRouter, Depends, Request, HTTPException
from fastapi.responses import FileResponse
import os
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.database import get_db
from app.schemas.agent import AgentEnrollRequest, AgentEnrollResponse, AgentHeartbeatRequest, AgentHeartbeatResponse
from app.services.agent_service import AgentService
from app.api.deps import get_current_agent
from app.models.device import Device

router = APIRouter(tags=["Agent - Protocole"])


@router.post("/enroll", response_model=AgentEnrollResponse)
async def enroll_agent(
    enroll_in: AgentEnrollRequest,
    request: Request,
    db: AsyncSession = Depends(get_db)
):
    service = AgentService(db)
    client_ip = request.client.host if request.client else None
    return await service.enroll_agent(enroll_in, ip_address=client_ip)


@router.post("/heartbeat", response_model=AgentHeartbeatResponse)
async def heartbeat(
    heartbeat_in: AgentHeartbeatRequest,
    request: Request,
    device: Device = Depends(get_current_agent),
    db: AsyncSession = Depends(get_db)
):
    service = AgentService(db)
    client_ip = request.client.host if request.client else None
    return await service.process_heartbeat(device, heartbeat_in, ip_address=client_ip)


@router.get("/download/windows")
async def download_windows_agent():
    """
    Téléchargement direct du binaire Windows mapt-agent.exe
    """
    candidate_paths = [
        "/app/agent-windows/mapt-agent.exe",
        "/agent/mapt-agent.exe",
        "/app/agent/mapt-agent.exe",
        "/app/static/mapt-agent.exe",
        "/app/mapt-agent.exe",
        os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../../agent/mapt-agent.exe")),
        "/mnt/c/Users/Admin/Documents/Github/MAPT/agent/mapt-agent.exe",
        os.path.abspath("agent/mapt-agent.exe"),
    ]

    for p in candidate_paths:
        if os.path.exists(p) and os.path.isfile(p):
            return FileResponse(
                path=p,
                filename="mapt-agent.exe",
                media_type="application/vnd.microsoft.portable-executable"
            )

    raise HTTPException(status_code=404, detail="Binaire mapt-agent.exe non trouvé sur le serveur.")


@router.get("/install.ps1")
@router.get("/install-agent.ps1")
async def get_agent_installer_script(request: Request, token: str = None):
    """
    Génère dynamiquement le script PowerShell d'installation, compatible avec TOUTES les versions
    de PowerShell (PS 2.0, 3.0, 4.0, 5.0, 5.1, 7.x) et Windows 7/8/10/11/Server.
    """
    from fastapi.responses import PlainTextResponse
    from app.core.config import settings

    proto = request.headers.get("x-forwarded-proto", "http")
    host = request.headers.get("host", str(request.base_url.netloc) if request.base_url else "127.0.0.1")
    base_url = f"{proto}://{host}".rstrip("/")
    enroll_token = token or settings.DEFAULT_ENROLLMENT_TOKEN

    ps1_content = f"""# MAPT Agent Windows Automated Installer (Universal Compatibility: PS 2.0 -> 7+)
# Generated by MAPT Server ({base_url})
$ErrorActionPreference = "Continue"

# 0. Configuration TLS sécurisée compatible toutes versions .NET (2.0/3.5/4.x/Core)
try {{
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]'Tls12,Tls11,Tls'
}} catch {{
    try {{
        [System.Net.ServicePointManager]::SecurityProtocol = 3072 -bor 768 -bor 192
    }} catch {{}}
}}

$serverUrl = "{base_url}/api/v1"
$downloadUrl = "$serverUrl/agent/download/windows"
$enrollToken = "{enroll_token}"
$installDir = "$env:ProgramFiles\\MAPT"

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "  MAPT - Installation Automatisée de l'Agent Windows       " -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan

# 1. Vérification des droits Administrateur
$isAdmin = $false
try {{
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    $isAdmin = $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}} catch {{
    $isAdmin = $true
}}

if (-not $isAdmin) {{
    Write-Host "[!] ERREUR : Ce script doit être exécuté dans une invite PowerShell Administrateur." -ForegroundColor Red
    exit 1
}}

# 2. Création du dossier d'installation
if (-not (Test-Path -Path $installDir)) {{
    Write-Host "[*] Création du dossier $installDir..." -ForegroundColor Yellow
    [System.IO.Directory]::CreateDirectory($installDir) | Out-Null
}}

$agentExe = Join-Path $installDir "mapt-agent.exe"

# 3. Arrêt du service existant s'il tourne déjà
try {{
    $existingService = Get-Service -Name "mapt-agent" -ErrorAction SilentlyContinue
    if ($existingService) {{
        Write-Host "[*] Arrêt du service MAPT existant..." -ForegroundColor Yellow
        Stop-Service -Name "mapt-agent" -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2
    }}
}} catch {{}}

# 4. Téléchargement robuste multi-méthodes (WebClient / Invoke-WebRequest / curl / certutil / BITS)
Write-Host "[*] Téléchargement de l'agent depuis $downloadUrl..." -ForegroundColor Yellow
$downloadSuccess = $false

# Méthode A : System.Net.WebClient (Universal .NET 2.0+)
if (-not $downloadSuccess) {{
    try {{
        $wc = New-Object System.Net.WebClient
        $wc.Headers.Add("User-Agent", "MAPT-Bootstrap-Installer")
        $wc.DownloadFile($downloadUrl, $agentExe)
        if ((Test-Path $agentExe) -and ((Get-Item $agentExe).Length -gt 1000000)) {{
            $downloadSuccess = $true
        }}
    }} catch {{}}
}}

# Méthode B : Invoke-WebRequest
if (-not $downloadSuccess) {{
    try {{
        Invoke-WebRequest -Uri $downloadUrl -OutFile $agentExe -UseBasicParsing -ErrorAction Stop
        if ((Test-Path $agentExe) -and ((Get-Item $agentExe).Length -gt 1000000)) {{
            $downloadSuccess = $true
        }}
    }} catch {{}}
}}

# Méthode C : curl.exe
if (-not $downloadSuccess) {{
    try {{
        & curl.exe -s -L -o "$agentExe" "$downloadUrl"
        if ((Test-Path $agentExe) -and ((Get-Item $agentExe).Length -gt 1000000)) {{
            $downloadSuccess = $true
        }}
    }} catch {{}}
}}

# Méthode D : certutil.exe
if (-not $downloadSuccess) {{
    try {{
        & certutil.exe -urlcache -split -f "$downloadUrl" "$agentExe" | Out-Null
        if ((Test-Path $agentExe) -and ((Get-Item $agentExe).Length -gt 1000000)) {{
            $downloadSuccess = $true
        }}
    }} catch {{}}
}}

if (-not $downloadSuccess -or -not (Test-Path $agentExe)) {{
    Write-Host "[!] Échec du téléchargement du binaire mapt-agent.exe depuis $downloadUrl" -ForegroundColor Red
    exit 1
}}

$fileSize = (Get-Item $agentExe).Length
Write-Host "[+] Binaire téléchargé avec succès ($fileSize octets)" -ForegroundColor Green

# 5. Enregistrement et Démarrage du Service Windows
Write-Host "[*] Configuration et enregistrement du service Windows..." -ForegroundColor Yellow
try {{
    & "$agentExe" -service uninstall 2>&1 | Out-Null
}} catch {{}}

& "$agentExe" -service install -server "$serverUrl" -enroll-token "$enrollToken"
Start-Sleep -Seconds 2

Write-Host "[*] Démarrage du service Windows..." -ForegroundColor Yellow
& "$agentExe" -service start
Start-Sleep -Seconds 2

$finalService = Get-Service -Name "mapt-agent" -ErrorAction SilentlyContinue
if ($finalService -and $finalService.Status -eq "Running") {{
    Write-Host ""
    Write-Host "==========================================================" -ForegroundColor Green
    Write-Host "  [OK] AGENT MAPT INSTALLE ET DEMARRE AVEC SUCCES !       " -ForegroundColor Green
    Write-Host "==========================================================" -ForegroundColor Green
}} else {{
    Write-Host "[*] Statut actuel du service : $($finalService.Status)" -ForegroundColor Yellow
}}
"""
    return PlainTextResponse(content=ps1_content, media_type="text/plain; charset=utf-8")


@router.get("/install.bat")
@router.get("/install-agent.bat")
async def get_agent_installer_batch(request: Request, token: str = None):
    """
    Génère un script Batch (.bat) pour déploiement via Invite de commandes classique, GPO ou Snapin FOG.
    """
    from fastapi.responses import PlainTextResponse
    from app.core.config import settings

    proto = request.headers.get("x-forwarded-proto", "http")
    host = request.headers.get("host", str(request.base_url.netloc) if request.base_url else "127.0.0.1")
    base_url = f"{proto}://{host}".rstrip("/")
    enroll_token = token or settings.DEFAULT_ENROLLMENT_TOKEN

    bat_content = f"""@echo off
setlocal enabledelayedexpansion
title Installation Agent MAPT

echo ==========================================================
echo   MAPT - Installation Automatisée de l'Agent Windows (.BAT)
echo ==========================================================

set "SERVER_URL={base_url}/api/v1"
set "DOWNLOAD_URL=%SERVER_URL%/agent/download/windows"
set "ENROLL_TOKEN={enroll_token}"
set "INSTALL_DIR=%ProgramFiles%\\MAPT"
set "AGENT_EXE=%INSTALL_DIR%\\mapt-agent.exe"

if not exist "%INSTALL_DIR%" (
    mkdir "%INSTALL_DIR%"
)

echo [*] Arret de l'ancien service s'il existe...
net stop mapt-agent >nul 2>&1

echo [*] Telechargement de mapt-agent.exe...
curl.exe -s -L -o "%AGENT_EXE%" "%DOWNLOAD_URL%"
if not exist "%AGENT_EXE%" (
    powershell -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; (New-Object System.Net.WebClient).DownloadFile('%DOWNLOAD_URL%', '%AGENT_EXE%')"
)

if not exist "%AGENT_EXE%" (
    echo [!] Erreur: Impossible de telecharger mapt-agent.exe
    exit /b 1
)

echo [*] Enregistrement du service Windows...
"%AGENT_EXE%" -service uninstall >nul 2>&1
"%AGENT_EXE%" -service install -server "%SERVER_URL%" -enroll-token "%ENROLL_TOKEN%"

echo [*] Demarrage du service Windows...
"%AGENT_EXE%" -service start

echo [OK] Agent MAPT installe et operationnel.
exit /b 0
"""
    return PlainTextResponse(content=bat_content, media_type="text/plain; charset=utf-8")


