from fastapi import APIRouter, Depends, Request, HTTPException
from fastapi.responses import FileResponse
import os
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.database import get_db
from app.schemas.agent import AgentEnrollRequest, AgentEnrollResponse, AgentHeartbeatRequest, AgentHeartbeatResponse
from app.services.agent_service import AgentService
from app.api.deps import get_current_agent
from app.models.device import Device

router = APIRouter(tags=["Agent - Protocole"])


@router.post("/enroll", response_model=AgentEnrollResponse)
async def enroll_agent(
    enroll_in: AgentEnrollRequest,
    request: Request,
    db: AsyncSession = Depends(get_db)
):
    service = AgentService(db)
    client_ip = request.client.host if request.client else None
    return await service.enroll_agent(enroll_in, ip_address=client_ip)


@router.post("/heartbeat", response_model=AgentHeartbeatResponse)
async def heartbeat(
    heartbeat_in: AgentHeartbeatRequest,
    request: Request,
    device: Device = Depends(get_current_agent),
    db: AsyncSession = Depends(get_db)
):
    service = AgentService(db)
    client_ip = request.client.host if request.client else None
    return await service.process_heartbeat(device, heartbeat_in, ip_address=client_ip)


@router.get("/download/windows")
async def download_windows_agent():
    """
    Téléchargement direct du binaire Windows mapt-agent.exe
    """
    candidate_paths = [
        "/agent/mapt-agent.exe",
        "/app/agent-windows/mapt-agent.exe",
        "/app/agent/mapt-agent.exe",
        "/app/static/mapt-agent.exe",
        "/app/mapt-agent.exe",
        os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../../agent/mapt-agent.exe")),
        "/mnt/c/Users/Admin/Documents/Github/MAPT/agent/mapt-agent.exe",
        os.path.abspath("agent/mapt-agent.exe"),
    ]

    for p in candidate_paths:
        if os.path.exists(p) and os.path.isfile(p):
            return FileResponse(
                path=p,
                filename="mapt-agent.exe",
                media_type="application/vnd.microsoft.portable-executable"
            )

    raise HTTPException(status_code=404, detail="Binaire mapt-agent.exe non trouvé sur le serveur.")


@router.get("/install.ps1")
@router.get("/install-agent.ps1")
async def get_agent_installer_script(request: Request, token: str = None):
    """
    Génère dynamiquement le script PowerShell d'installation, compatible avec TOUTES les versions
    de PowerShell (PS 2.0, 3.0, 4.0, 5.0, 5.1, 7.x) et Windows 7/8/10/11/Server.
    """
    from fastapi.responses import PlainTextResponse
    from app.core.config import settings

    proto = request.headers.get("x-forwarded-proto", "http")
    host = request.headers.get("host", str(request.base_url.netloc) if request.base_url else "127.0.0.1")
    base_url = f"{proto}://{host}".rstrip("/")
    enroll_token = token or settings.DEFAULT_ENROLLMENT_TOKEN

    ps1_content = f"""# MAPT Agent Windows Automated Installer (Universal Compatibility: PS 2.0 -> 7+)
# Generated by MAPT Server ({base_url})
$ErrorActionPreference = "Continue"

# 0. Configuration TLS sécurisée compatible toutes versions .NET (2.0/3.5/4.x/Core)
try {{
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]'Tls12,Tls11,Tls'
}} catch {{
    try {{
        [System.Net.ServicePointManager]::SecurityProtocol = 3072 -bor 768 -bor 192
    }} catch {{}}
}}

$serverUrl = "{base_url}/api/v1"
$cacheBuster = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
$downloadUrl = "$serverUrl/agent/download/windows?cb=$cacheBuster"
$enrollToken = "{enroll_token}"
$programFilesDir = if ($env:ProgramW6432) { $env:ProgramW6432 } else { $env:ProgramFiles }
$installDir = Join-Path $programFilesDir "MAPT"

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "  MAPT - Installation Automatisée de l'Agent Windows       " -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan

# 1. Vérification des droits Administrateur
$isAdmin = $false
try {
    $currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    $isAdmin = $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
} catch {
    $isAdmin = $true
}

if (-not $isAdmin) {
    Write-Host "[!] ERREUR : Ce script doit être exécuté dans une invite PowerShell Administrateur." -ForegroundColor Red
    exit 1
}

# 2. Création du dossier d'installation
if (-not (Test-Path -Path $installDir)) {
    Write-Host "[*] Création du dossier $installDir..." -ForegroundColor Yellow
    [System.IO.Directory]::CreateDirectory($installDir) | Out-Null
}

$agentExe = Join-Path $installDir "mapt-agent.exe"
$configFile = Join-Path $installDir "mapt-agent-config.json"

# 3. Arrêt complet du service existant et des processus résiduels
try {
    $existingService = Get-Service -Name "mapt-agent" -ErrorAction SilentlyContinue
    if ($existingService) {
        Write-Host "[*] Arrêt du service MAPT existant..." -ForegroundColor Yellow
        Stop-Service -Name "mapt-agent" -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 2
    }
} catch {}

try {
    Get-Process -Name "mapt-agent" -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 1
} catch {}

# 4. Téléchargement robuste multi-méthodes (WebClient / Invoke-WebRequest / curl / certutil)
Write-Host "[*] Téléchargement de l'agent depuis $downloadUrl..." -ForegroundColor Yellow
$downloadSuccess = $false

# Méthode A : System.Net.WebClient (Universal .NET 2.0+)
if (-not $downloadSuccess) {
    try {
        $wc = New-Object System.Net.WebClient
        $wc.Headers.Add("User-Agent", "MAPT-Bootstrap-Installer")
        $wc.DownloadFile($downloadUrl, $agentExe)
        if ((Test-Path $agentExe) -and ((Get-Item $agentExe).Length -gt 1000000)) {
            $downloadSuccess = $true
        }
    } catch {}
}

# Méthode B : Invoke-WebRequest
if (-not $downloadSuccess) {
    try {
        Invoke-WebRequest -Uri $downloadUrl -OutFile $agentExe -UseBasicParsing -ErrorAction Stop
        if ((Test-Path $agentExe) -and ((Get-Item $agentExe).Length -gt 1000000)) {
            $downloadSuccess = $true
        }
    } catch {}
}

# Méthode C : curl.exe
if (-not $downloadSuccess) {
    try {
        & curl.exe -s -L -o "$agentExe" "$downloadUrl"
        if ((Test-Path $agentExe) -and ((Get-Item $agentExe).Length -gt 1000000)) {
            $downloadSuccess = $true
        }
    } catch {}
}

# Méthode D : certutil.exe
if (-not $downloadSuccess) {
    try {
        & certutil.exe -urlcache -split -f "$downloadUrl" "$agentExe" | Out-Null
        if ((Test-Path $agentExe) -and ((Get-Item $agentExe).Length -gt 1000000)) {
            $downloadSuccess = $true
        }
    } catch {}
}

if (-not $downloadSuccess -or -not (Test-Path $agentExe)) {
    Write-Host "[!] Échec du téléchargement du binaire mapt-agent.exe depuis $downloadUrl" -ForegroundColor Red
    exit 1
}

$fileSize = (Get-Item $agentExe).Length
Write-Host "[+] Binaire téléchargé avec succès ($fileSize octets)" -ForegroundColor Green

# 5. Création / Mise à jour du fichier de configuration mapt-agent-config.json
Write-Host "[*] Configuration de l'identifiant machine persistant..." -ForegroundColor Yellow
$deviceUuid = ""
if (Test-Path $configFile) {
    try {
        $existingCfg = Get-Content $configFile -Raw | ConvertFrom-Json
        if ($existingCfg.device_uuid) { $deviceUuid = $existingCfg.device_uuid }
    } catch {}
}
if (-not $deviceUuid) {
    try {
        $deviceUuid = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Cryptography" -Name MachineGuid -ErrorAction SilentlyContinue).MachineGuid
    } catch {}
}
if (-not $deviceUuid) {
    try {
        $deviceUuid = (Get-CimInstance -Class Win32_ComputerSystemProduct -ErrorAction SilentlyContinue).UUID
    } catch {}
}
if (-not $deviceUuid) {
    $deviceUuid = [Guid]::NewGuid().ToString()
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$configContent = @'
{{
  "server_url": "__SERVER_URL__",
  "enrollment_token": "__ENROLL_TOKEN__",
  "agent_token": "",
  "device_uuid": "__DEVICE_UUID__",
  "log_level": "info",
  "heartbeat_interval_seconds": 30,
  "job_poll_interval_seconds": 15,
  "inventory_interval_seconds": 3600
}}
'@
$configContent = $configContent.Replace("__SERVER_URL__", $serverUrl).Replace("__ENROLL_TOKEN__", $enrollToken).Replace("__DEVICE_UUID__", $deviceUuid)

if (-not (Test-Path $configFile)) {{
    [System.IO.File]::WriteAllText($configFile, $configContent, $utf8NoBom)
}} else {{
    try {{
        $existingCfg = Get-Content $configFile -Raw | ConvertFrom-Json
        $existingCfg.server_url = $serverUrl
        if ($enrollToken) {{ $existingCfg.enrollment_token = $enrollToken }}
        if (-not $existingCfg.device_uuid) {{ $existingCfg.device_uuid = $deviceUuid }}
        $jsonStr = $existingCfg | ConvertTo-Json -Depth 5
        [System.IO.File]::WriteAllText($configFile, $jsonStr, $utf8NoBom)
    }} catch {{
        [System.IO.File]::WriteAllText($configFile, $configContent, $utf8NoBom)
    }}
}}

# 6. Enregistrement et Démarrage du Service Windows
Write-Host "[*] Configuration et enregistrement du service Windows..." -ForegroundColor Yellow
try {{
    & "$agentExe" -service uninstall 2>&1 | Out-Null
    Start-Sleep -Seconds 1
}} catch {{}}

# Méthode 1: Agent auto-enregistrement
try {{
    & "$agentExe" -service install -config "$configFile" -server "$serverUrl" -enroll-token "$enrollToken" 2>&1 | Out-Null
    Start-Sleep -Seconds 1
}} catch {{}}

# Méthode 2: Fallback direct via sc.exe si le service n'est pas encore présent
$svc = Get-Service -Name "mapt-agent" -ErrorAction SilentlyContinue
if (-not $svc) {{
    & sc.exe create "mapt-agent" binPath= "`"$agentExe`" -config `"$configFile`"" start= auto DisplayName= "MAPT Endpoint Agent" | Out-Null
    & sc.exe description "mapt-agent" "Service d'administration, d'inventaire et de telemetrie MAPT pour Windows" | Out-Null
    Start-Sleep -Seconds 1
}}

Write-Host "[*] Démarrage du service Windows..." -ForegroundColor Yellow
try {{
    Start-Service -Name "mapt-agent" -ErrorAction SilentlyContinue
}} catch {{}}

try {{
    & "$agentExe" -service start 2>&1 | Out-Null
}} catch {{}}

try {{
    & sc.exe start "mapt-agent" 2>&1 | Out-Null
}} catch {{}}

Start-Sleep -Seconds 3

$finalService = Get-Service -Name "mapt-agent" -ErrorAction SilentlyContinue
if ($finalService -and $finalService.Status -eq "Running") {{
    Write-Host ""
    Write-Host "==========================================================" -ForegroundColor Green
    Write-Host "  [OK] AGENT MAPT INSTALLE ET DEMARRE AVEC SUCCES !       " -ForegroundColor Green
    Write-Host "==========================================================" -ForegroundColor Green
}} else {{
    Write-Host "[*] Statut actuel du service : $($finalService.Status)" -ForegroundColor Yellow
}}
"""
    return PlainTextResponse(content=ps1_content, media_type="text/plain; charset=utf-8")


@router.get("/install.bat")
@router.get("/install-agent.bat")
async def get_agent_installer_batch(request: Request, token: str = None):
    """
    Génère un script Batch (.bat) pour déploiement via Invite de commandes classique, GPO ou Snapin FOG.
    """
    from fastapi.responses import PlainTextResponse
    from app.core.config import settings

    proto = request.headers.get("x-forwarded-proto", "http")
    host = request.headers.get("host", str(request.base_url.netloc) if request.base_url else "127.0.0.1")
    base_url = f"{proto}://{host}".rstrip("/")
    enroll_token = token or settings.DEFAULT_ENROLLMENT_TOKEN

    bat_content = f"""@echo off
setlocal enabledelayedexpansion
title Installation Agent MAPT

echo ==========================================================
echo   MAPT - Installation Automatisée de l'Agent Windows (.BAT)
echo ==========================================================

set "SERVER_URL={base_url}/api/v1"
set "DOWNLOAD_URL=%SERVER_URL%/agent/download/windows"
set "ENROLL_TOKEN={enroll_token}"
if defined ProgramW6432 (
    set "INSTALL_DIR=%ProgramW6432%\\MAPT"
) else (
    set "INSTALL_DIR=%ProgramFiles%\\MAPT"
)
set "AGENT_EXE=%INSTALL_DIR%\\mapt-agent.exe"
set "CONFIG_FILE=%INSTALL_DIR%\\mapt-agent-config.json"

if not exist "%INSTALL_DIR%" (
    mkdir "%INSTALL_DIR%"
)

echo [*] Arret de l'ancien service s'il existe...
net stop mapt-agent >nul 2>&1

echo [*] Telechargement de mapt-agent.exe...
curl.exe -s -L -o "%AGENT_EXE%" "%DOWNLOAD_URL%"
if not exist "%AGENT_EXE%" (
    powershell -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; (New-Object System.Net.WebClient).DownloadFile('%DOWNLOAD_URL%', '%AGENT_EXE%')"
)

if not exist "%AGENT_EXE%" (
    echo [!] Erreur: Impossible de telecharger mapt-agent.exe
    exit /b 1
)

echo [*] Enregistrement et demarrage du service Windows...
sc stop mapt-agent >nul 2>&1
sc delete mapt-agent >nul 2>&1
"%AGENT_EXE%" -service install -server "%SERVER_URL%" -enroll-token "%ENROLL_TOKEN%" >nul 2>&1
sc create "mapt-agent" binPath= "\"%AGENT_EXE%\" -config \"%CONFIG_FILE%\"" start= auto DisplayName= "MAPT Endpoint Agent" >nul 2>&1
sc description "mapt-agent" "Service d'administration, d'inventaire et de telemetrie MAPT pour Windows" >nul 2>&1
net start mapt-agent

echo [OK] Agent MAPT installe et operationnel.
exit /b 0
"""
    return PlainTextResponse(content=bat_content, media_type="text/plain; charset=utf-8")


